---
title: "DSC640_Exercise_2-2_JakeMeyer"
course: "DSC 640 Data Presentation & Visualization (DSC640-T302 2231-1)"
college: "Bellevue University"
author: "Jake Meyer"
date: "2022-12-12"
output: pdf_document
always_allow_html: yes
---

```{r setup, include=FALSE}
library(knitr)
knitr::opts_chunk$set(echo = TRUE, 
                      root.dir = "C:/Users/jkmey/Documents/Github/DSC640_Course_Assignments/DSC640_Repository" )
```

## Assignment Instructions
Submit 1 line chart and 1 step chart with R.

### Show Working directory
```{r, warning = FALSE}
getwd()
dir()
 # setwd("C:/Users/jkmey/Documents/Github/DSC640_Course_Assignments/DSC640_Repository")
```

### Import the necessary libraries
```{r, warning = FALSE}
library(readxl)
library(ggplot2)
library(tidyverse)
library(dplyr)
library(scales)
library(plotly)
theme_set(theme_minimal())
```

### Import the data
```{r}
df1 <- read_excel("world-population.xlsm")
```

### Line Chart
```{r}
ggplot(df1, aes(x = Year, y = Population, group = 1)) + 
  geom_line() + xlab('Year') + ylab('Population (Billion)') + 
  ggtitle('Population by Year (Line Chart)') + 
  scale_y_continuous(labels = label_number(suffix = "B", scale = 1e-9))
```
### Step Chart
```{r}
p <- ggplot(df1, aes(Year,Population)) + geom_step() + xlab('Year') +
  ylab('Population (Billion)') + 
  ggtitle('Population by Year (Step Chart)') + 
  scale_y_continuous(labels = label_number(suffix = "B", scale = 1e-9))

plotly::ggplotly(p)
```