---
title: "DSC640_Exercise_3-2_JakeMeyer"
course: "DSC 640 Data Presentation & Visualization (DSC640-T302 2231-1)"
college: "Bellevue University"
author: "Jake Meyer"
date: "2023-01-14"
output: pdf_document
always_allow_html: yes
---

```{r setup, include=FALSE}
library(knitr)
knitr::opts_chunk$set(echo = TRUE, 
                      root.dir = "C:/Users/jkmey/Documents/Github/DSC640_Course_Assignments/DSC640_Repository" )
```

## Assignment Instructions
Submit 1 tree map, 1 area chart, and 1 stacked area chart with R.

### Show Working directory
```{r, warning = FALSE}
getwd()
dir()
 # setwd("C:/Users/jkmey/Documents/Github/DSC640_Course_Assignments/DSC640_Repository")
```

### Import the necessary libraries
```{r, warning = FALSE}
library(readxl)
library(ggplot2)
library(tidyverse)
library(dplyr)
library(scales)
library(plotly)
library(treemap)
library(RColorBrewer)
library(treemapify)
theme_set(theme_minimal())
```

### Import the data
```{r}
df1 <- read.table("expenditures.txt", header = TRUE, sep = "\t")
```

### Tree Map using treemap()
```{r}
treemap(df1, index = c('category'), vSize = 'expenditure',
        title = "Tree Map of Expenditure Data", fontsize.labels = c(10, 8),
        align.labels = list(c('centre','centre'),c('left','top')))
```
```{r}
df_agg <- aggregate(expenditure ~ category, df1, sum)
df_agg
```

### Tree Map using ggplot2 and treemapify
```{r}
ggplot(df_agg, aes(area = expenditure, fill = category,
                label = paste(category, expenditure, sep = "\n"))) + 
  geom_treemap() + geom_treemap_text(colour = "white",
                                     place = "centre",
                                     size = 15) + 
  ggtitle("Tree Map of Expenditure Data by Category ($)")
```

### Area Chart
```{r}
ggplot(df1, aes(x = year, fill = category)) + 
  geom_area(aes(y = expenditure), position = position_dodge(), alpha = 0.6) +
  geom_line(aes(y=expenditure)) +
  ggtitle("Area Chart of Expenditures by Category") + xlab("Year") + 
  ylab("Expenditure ($)") 
```

### Stacked Area Chart
```{r}
ggplot(df1, aes(x = year, fill = category)) + geom_area(aes(y = expenditure)) +
  ggtitle("Stacked Area Chart of Expenditures by Category") + xlab("Year") + 
  ylab("Expenditure ($)")
```
